import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useQuery} from "@tanstack/react-query";
import Link from "next/link";

const Home: NextPage = () => {

    const fetchPokemon = () => {
        return fetch("https://pokeapi.co/api/v2/pokemon").then((res) =>
            res.json()
        )
    }

    const {data} = useQuery(['pokemon'], fetchPokemon)
    if (!data) return null
    const pokemones = data.results

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description}>
                    Get started by editing{' '}
                    <code className={styles.code}>pages/index.tsx</code>
                </p>

                <div className={styles.grid}>
                    {pokemones.map((poke: any) => {
                        return (
                            <Link key={poke.name} href={poke.name}>
                                <div className={styles.card}>
                                    <h2>{poke.name}</h2>
                                </div>
                            </Link>
                        )
                    })}

                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}

export default Home